#!/usr/bin/env python3
"""
scripts/build_payload.py
Compiles kfs_jsons/ + scratch/template.html into:
    - data/kfs-payload.js, used by this validation app
    - dist/kfs-template.html + dist/kfs-jsons.json, used for app embedding

Usage:
    python3 scripts/build_payload.py

Outputs:
    data/kfs-payload.js  — sets window.KFS_PAYLOAD = "<base64-gzipped-json>"
    dist/kfs-template.html — standalone source-truth template
    dist/kfs-jsons.json — all language copy bundled by language key

The payload JSON structure is:
    {
        "template": "<full HTML template string>",
        "jsons": {
            "english": { ... },
            "hindi":   { ... },
            ...
        }
    }
"""

import json
import gzip
import base64
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_PATH = os.path.join(REPO_ROOT, "scratch", "template.html")
JSONS_DIR = os.path.join(REPO_ROOT, "kfs_jsons")
OUTPUT_PATH = os.path.join(REPO_ROOT, "data", "kfs-payload.js")
DIST_DIR = os.path.join(REPO_ROOT, "dist")
DIST_TEMPLATE_PATH = os.path.join(DIST_DIR, "kfs-template.html")
DIST_JSONS_PATH = os.path.join(DIST_DIR, "kfs-jsons.json")


def load_template():
    if not os.path.exists(TEMPLATE_PATH):
        print(f"ERROR: Template not found at {TEMPLATE_PATH}", file=sys.stderr)
        sys.exit(1)
    with open(TEMPLATE_PATH, "r", encoding="utf-8") as f:
        content = f.read()
    # The template file may start with `window.KFS_TEMPLATE = "..."` or just be raw HTML
    # Strip JS wrapper if present
    if content.startswith("window.KFS_TEMPLATE"):
        # Extract the string value between the outer quotes
        import re
        m = re.match(r'window\.KFS_TEMPLATE\s*=\s*"([\s\S]*)"\s*;\s*$', content)
        if m:
            import codecs
            # Unescape JS string escapes
            raw = m.group(1)
            content = raw.encode("raw_unicode_escape").decode("unicode_escape")
        else:
            print("ERROR: Could not parse template.html JS wrapper.", file=sys.stderr)
            sys.exit(1)
    return content


def load_jsons():
    if not os.path.isdir(JSONS_DIR):
        print(f"ERROR: kfs_jsons/ not found at {JSONS_DIR}", file=sys.stderr)
        sys.exit(1)

    jsons = {}
    for filename in sorted(os.listdir(JSONS_DIR)):
        if not filename.endswith(".json"):
            continue
        lang = filename[:-5]  # strip .json
        if lang.startswith("_"):
            print(f"  [skip] {filename}")
            continue
        with open(os.path.join(JSONS_DIR, filename), "r", encoding="utf-8") as f:
            jsons[lang] = json.load(f)
        print(f"  [load] {filename}  ({len(jsons[lang])} keys)")
    return jsons


def build():
    print("Building KFS payload...")
    print(f"  Template:  {TEMPLATE_PATH}")
    print(f"  JSONs dir: {JSONS_DIR}")
    print(f"  Output:    {OUTPUT_PATH}")
    print()

    template = load_template()
    jsons = load_jsons()

    payload = {"template": template, "jsons": jsons}
    json_str = json.dumps(payload, ensure_ascii=False)
    gzipped = gzip.compress(json_str.encode("utf-8"), compresslevel=9)
    b64 = base64.b64encode(gzipped).decode("ascii")

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(f"// Auto-generated by scripts/build_payload.py — do not hand-edit.\n")
        f.write(f"// Languages: {', '.join(sorted(jsons.keys()))}\n")
        f.write(f'window.KFS_PAYLOAD = "{b64}";\n')

    os.makedirs(DIST_DIR, exist_ok=True)
    with open(DIST_TEMPLATE_PATH, "w", encoding="utf-8") as f:
        f.write(template)
    with open(DIST_JSONS_PATH, "w", encoding="utf-8") as f:
        json.dump(jsons, f, ensure_ascii=False, indent=2)
        f.write("\n")

    size_kb = os.path.getsize(OUTPUT_PATH) / 1024
    template_kb = os.path.getsize(DIST_TEMPLATE_PATH) / 1024
    jsons_kb = os.path.getsize(DIST_JSONS_PATH) / 1024
    print(f"\n✓ Done — {OUTPUT_PATH} ({size_kb:.1f} KB, {len(jsons)} languages)")
    print(f"✓ Handoff — {DIST_TEMPLATE_PATH} ({template_kb:.1f} KB)")
    print(f"✓ Handoff — {DIST_JSONS_PATH} ({jsons_kb:.1f} KB)")


if __name__ == "__main__":
    build()
